import Image from 'next/image'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        <Image src="/float.svg" alt='float' width={500} height={500} className='figure' />
        <Image src="/float2.svg" alt='float2' width={500} height={500} className='figure2' />
        {children}
      </body>
    </html>
  )
}
